version: '3'

services:
  backend:
    build: ./server
    volumes:
      - ./server:/backend
    ports:
      - 5000:5000

  react:
    build: ./react
    volumes:
      - ./react:/frontend
    ports:
      - 8080:80
      - 443:443
