version: '3'

services:
  backend:
    build: ./server
    volumes:
      - ./server:/backend
    ports:
      - 5000:5000

  react:
    build: ./react
    volumes:
      - ./react:/frontend
    ports:
      - 8080:80
      - 443:443

  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
       POSTGRES_DB: visualsupport
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 2016
    volumes:
      - /var/lib/postgresql/data
